### ISSUE TITLE
你好  第一步就不会了

### ISSUE THREAD

**Issue by s78910** [yige233/fast_yiban#1]
你好大佬   1.安装最新的nodejs   
这个第一部开始就没找到怎么安装    请问可以加下联系方式请教你吗     我的微信 S78910JQKKKAA

**Comment by yige233** [comment]
readme更新了，你看看还懂不懂

**Comment by org256w** [comment]
与服务器的连接似乎出了问题，请刷新或联系管理员！是什么情况
![微信截图_20220602155137](https://user-images.githubusercontent.com/106732434/171581650-d591b629-494b-4a03-9fd5-b7699661bbfa.png)

**Comment by yige233** [comment]
请在浏览器里打开 http://localhost:4500
而不是双击public里的index.html



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月2日(周四) 下午3:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [yige233/fast_yiban] 你好  第一步就不会了 (Issue #1)




 
与服务器的连接似乎出了问题，请刷新或联系管理员！是什么情况

**Comment by org256w** [comment]
感谢up ，已经成功打开了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yige233/fast_yiban"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月2日(星期四) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yige233/fast_yiban] 你好  第一步就不会了 (Issue #1)





 请在浏览器里打开 http://localhost:4500 
 而不是双击public里的index.html 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年6月2日(周四) 下午3:53 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [yige233/fast_yiban] 你好  第一步就不会了 (Issue #1) 
 
 
 
 
   
 与服务器的连接似乎出了问题，请刷新或联系管理员！是什么情况
