### ISSUE TITLE
建议新功能

### ISSUE THREAD

**Issue by SHIKO-ZHOU** [yige233/fast_yiban#10]
可否加个默认定位位置，每天划来划去选点有点浪费时间😭

**Comment by yige233** [comment]
有道理，这两天就做
主要是如果能自动打卡的话，每天打开链接就好了，所以没有充分考虑到不能自动打卡的情况

**Comment by yige233** [comment]
现在程序应该能满足你的需求了，虽然不太像传统意义上的“默认”……你可以先看看readme里的[如何打卡？](https://github.com/yige233/fast_yiban/blob/main/README.md#%E5%A6%82%E4%BD%95%E6%89%93%E5%8D%A1)一节，如果遇到哪里不懂，可以在这个issue里问我

**Comment by SHIKO-ZHOU** [comment]
好吧是我对程序不太熟悉，刚刚发现可以通过打过的url快速打卡，还有一个昨天打卡，签名无法显示，我是本地上传一个png图，是通过转发表单，转发后的表单上下载的签名图

**Comment by SHIKO-ZHOU** [comment]
上传类型为url，将通过服务器直接上传
20:01:09 file is not defined

图片链接
https://supcache.miancp.com/data/shiko.vip/61d3441cb3a3e4b7dc8b9e213b84f937.png


![image](https://user-images.githubusercontent.com/54561881/204272961-832b5326-65e9-41e4-bcea-78f0b6bdbb9b.png)

**Comment by SHIKO-ZHOU** [comment]
直接上传的话可以，但是图片显示不出来

![image](https://user-images.githubusercontent.com/54561881/204273256-9894a357-03de-4ae5-97e9-b42370b1931d.png)

**Comment by yige233** [comment]
url上传不了的原因找到了，是我代码里有东西没删干净（裂开
但显示不了图片应该和怎么上传的没关系，具体原因我还在研究

**Comment by SHIKO-ZHOU** [comment]
更新到最新版本后，url打卡会要求提交签名，上个版本不会

**Comment by yige233** [comment]
OK，我已经找到问题所在了，显示不了图片的原因是代码中没能正确处理签名图数据，此前发送的数据是错误的所以显示不出来

**Comment by SHIKO-ZHOU** [comment]
完美解决了，非常感谢
