### ISSUE TITLE
获取任务列表出错:无权限访问

### ISSUE THREAD

**Issue by alayyyy** [yige233/fast_yiban#12]
提示：获取任务列表出错:无权限访问
貌似接口崩了？

**Comment by yige233** [comment]
我拿我自己的账号试了试，没有出现无权限的提示，请问你能正常通过易班app访问校本化的任务列表界面吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月8日(周一) 晚上9:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yige233/fast_yiban] 获取任务列表出错:无权限访问 (Issue #12)




 
提示：获取任务列表出错:无权限访问
 貌似接口崩了？

**Comment by alayyyy** [comment]
我们的易班校本化并没有这个界面

**Comment by yige233** [comment]
那你能提供一些你们校本化的截图吗？我推测是虽然都叫校本化，但是它们实际上不是同一套系统



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月8日(周一) 晚上10:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yige233/fast_yiban] 获取任务列表出错:无权限访问 (Issue #12)




 
我们的易班校本化并没有这个界面
