### ISSUE TITLE
表单不完整

### ISSUE THREAD

**Issue by JBright1030** [yige233/fast_yiban#2]
最下面还有个输入框出不来。
![F04348B4-D5BC-4E4D-9638-7EA87E027902](https://user-images.githubusercontent.com/96562241/178130532-4bd0d1b6-7da0-477d-bac5-951e10b457bb.jpeg)

**Comment by yige233** [comment]
有办法打开控制台吗？控制台里应该会有给出是什么类型的输入框



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月10日(周日) 中午11:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yige233/fast_yiban] 表单不完整 (Issue #2)




 
最下面还有个输入框出不来。

**Comment by JBright1030** [comment]
应该是跟第一个输入框一样的吧，你说的那个我不会操作
![屏幕截图 2022-07-10 184600](https://user-images.githubusercontent.com/96562241/178141713-5257f9ff-c894-4ca1-a433-c4e5c45114a8.png)

**Comment by yige233** [comment]
虽然这两者表现上应该是一样的，但是在程序层面它们是两个不一样的输入框；而那个不显示的输入框到底是啥，得到答案的办法，一是你打开浏览器调试工具，然后告诉我；二是等我稍微修改下程序



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月10日(周日) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yige233/fast_yiban] 表单不完整 (Issue #2)




 
应该是跟第一个输入框一样的吧，你说的那个我不会操作

**Comment by JBright1030** [comment]
![F90638B1-C76D-4337-A245-300A2271B8CC](https://user-images.githubusercontent.com/96562241/178535024-285d8cb2-05b7-4799-bdb8-39d3c8fee3e1.jpeg)
现在成这样了，会显示文本类型
前面我抓包也是这种文本类型

**Comment by yige233** [comment]
了解了，看起来应该是需要输入数字，明天稍微改下代码就成，谢谢反馈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月12日(周二) 晚上11:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yige233/fast_yiban] 表单不完整 (Issue #2)




 

 现在成这样了，会显示文本类型
 前面我抓包也是这种文本类型

**Comment by JBright1030** [comment]
好嘞，感谢大佬！
