### ISSUE TITLE
大佬你好，关于易班打卡表单问题

### ISSUE THREAD

**Issue by SHIKO-ZHOU** [yige233/fast_yiban#3]
我们学校是有打卡表单里面是有手写签名的，实际我抓包发现他是直接将手写的转成png，然后以图片的形式提交，然后我在index.html.js里面加了case "Signature":
                    Imageurl(el, id, props);
                    break;

想让他以图片形式提交，但是实际打卡结果显示不了图片，能正常打卡成功，

附件是我抓到的有关提交签名的包
[签名.zip](https://github.com/yige233/fast_yiban/files/9791509/default.zip)

**Comment by yige233** [comment]
上传签名图的流程和上传普通图片似乎有一点小差别，两者可能在提交到易班的数据的结构上也有一些区别，可能是这个区别导致了易班不能正常显示图片
要解决这个问题就得搞清楚app提交给易班的数据的正常结构是怎么样的。
想办法抓一下 https://api.uyiban.com/workFlow/c/my/apply/ 的包，看看它发送的数据长啥样（我校的易班打卡没用到签名所以我没法自己抓
这个数据应该是加密的，index.js里有加密的函数，反过来就能解密


知道它的数据结构之后就好办了

**Comment by SHIKO-ZHOU** [comment]
这是我当时抓到的包
[提交.zip](https://github.com/yige233/fast_yiban/files/9810982/default.zip)

**Comment by yige233** [comment]
我看了你抓的数据，两者确实在结构上不同，但是能打卡成功挺奇怪的
普通图片的数据是一个数组，可以包含多张图片的信息；签名图的话，只有一个不完整的签名图url
所以不能直接套用上传普通图片的方法，要针对签名图修改相应代码才行，这几天我改改看

**Comment by SHIKO-ZHOU** [comment]
ok，麻烦了
