### ISSUE TITLE
地图填报完不显示位置

### ISSUE THREAD

**Issue by org256w** [yige233/fast_yiban#5]
打卡完成之后不显示地图的定位地点，直接显示空白

**Comment by yige233** [comment]
能否给出有问题的截图？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月18日(周二) 上午10:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yige233/fast_yiban] 地图填报完不显示位置 (Issue #5)




 
打卡完成之后不显示地图的定位地点，直接显示空白

**Comment by org256w** [comment]
这是易班正常的，左侧是填报表单，右侧是地图
 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
 
&nbsp;
 
&nbsp;
 
&nbsp;
 
这是咱们程序快速填报的，程序上选完位置之后，填报完表单上不现实，而且选址位置很长，

**Comment by yige233** [comment]
能从github再发一遍图吗，邮件里截图图好像裂了，没显示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月18日(周二) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yige233/fast_yiban] 地图填报完不显示位置 (Issue #5)




 这是易班正常的，左侧是填报表单，右侧是地图 
   
 &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;  
   
 &amp;nbsp; 
   
 &amp;nbsp; 
   
 &amp;nbsp; 
   
 这是咱们程序快速填报的，程序上选完位置之后，填报完表单上不现实，而且选址位置很长，

**Comment by org256w** [comment]
这是易班正常的，左侧是填报表单，右侧是地图
                
![image](https://user-images.githubusercontent.com/106732434/196434855-4a8c04cf-cfb7-4cf1-b6cc-97108ed04dbc.png)
![image](https://user-images.githubusercontent.com/106732434/196434918-fbf7d3c8-8934-4e03-9be3-33c3bf45a819.png)
这是咱们程序快速填报的，程序上选完位置之后，填报完表单上不现实，而且选址位置很长，
![image](https://user-images.githubusercontent.com/106732434/196435021-ae16d7a0-34ae-4106-8c10-e8c8144d1dc0.png)

![image](https://user-images.githubusercontent.com/106732434/196435041-1fd92061-b668-4942-95ec-283c6f5747b8.png)

**Comment by yige233** [comment]
我看了你用程序选址的结果，好像是两个正常地址拼到一块了，变成了“内蒙古……学院内蒙古……学院”，所以我猜测对应的经纬度可能也出现了类似问题，导致你在易班查看打卡结果的时候，易班的地图组件拿到的经纬度有误，没法显示

所以我的建议是，重新用程序选一遍地址，提交前检查各项都OK了，再提交

以及我的程序部署在国外的服务器上，而地图组件是从国内获取数据的，这样数据是：国内->国外->国内，延迟会很大，如果你在地图组件上点太快了，就可能导致某些bug

如果还是有问题，请在程序打卡成功的时候，先不要关闭网页，而是右键网页空白处，点击“检查”（或按下键盘上的F12键），在出现的Devtools页面中找到“控制台”，在控制台中输入`JSON.stringify(app.submit.submit)`。回车，然后把控制台输出的那一串字符完整复制过来

**Comment by org256w** [comment]
{"f6207a5af951ede5a7b9026eaf070b3c":"36.2","7a023091908325401912379247f2e364":"健康","0eb780597d181a6d0df8dffc5965dc5b":"正常、不属于以下情况","fffa7b08f67be7304c24748d01b10df1":"绿码","5ca9d124f4536af5e865a19b5ae1ac66":"是","75d398d15aaba088d46a7a03b993219d":"阴性","abcc2dc60485790c2e8e44bf8157c0ce":"否","2711b4a48e163be3c1fb8c0908b51261":"否","13504762a886a7e26cec7962eb50d3d4":"无","fe2eacad1056d9b6afaa759d09a0ab05":"是","197be2549035b7bf76f3d11ac9baa550":"否","aa68668ae53777b433ba329a3caa4f82":"低风险","b596a37984b08b30e17fc2338bc7d283":"否","12451b37384930b88048f04556763f5b":"否","20e0fbc372ff6f665fd9b9076d888071":"否","db7e890739acfad38e93531faff654a8":["内蒙古自治区","呼和浩特市","赛罕区"],"2c8d43d5aa3c2e96cc8445ad392dde47":{"location":111.854067,"name":"内蒙古自治区呼和浩特市赛罕区巴彦街道内蒙古电子信息职业技术学院3号宿舍楼","address":"内蒙古自治区呼和浩特市赛罕区巴彦街道内蒙古电子信息职业技术学院3号宿舍楼"},"57dbe2bda2ba5af5e1dc6225274d9552":"是"}

**Comment by yige233** [comment]
额，确实是我代码有问题。

易班地图定位有两种模式，一种上传的数据是将经纬度分开，另一种则是合在一起，我把两者搞混了……前者应该是这样的：
```
{
    longitude: 经度,
    latitude: 纬度
}
```
后者是这样的：
```
{
    location:"经度,纬度"
}
```
你们学校用的是后面一种，而因为我搞混了的关系，就导致后者经纬度信息不完整……

但神奇的是我们学校用的前一种定位模式，在这种情况下不会出现你说的问题……

而你提到的定位地址很长一串的问题，应该也是由于两种定位模式有所不同，后者在正常情况下获取到的不是完整的地址，但我的代码是获取完整地址，并套用到两种定位模式里。实际上没什么影响，主要还是经纬度不完整的问题。

关于经纬度的问题我已经在demo里修复了，你可以重新填一遍打卡信息试试。地址的问题还没有修复，不过后面会解决的。

**Comment by org256w** [comment]
大佬就是大佬，解决问题就是快啊，清晰明白我也明白代码哪里出现问题了，多的不说，感谢

**Comment by org256w** [comment]
有时间更新一下GitHub的代码哈哈
