### ISSUE TITLE
你好，关于打卡数据的问题

### ISSUE THREAD

**Issue by SHIKO-ZHOU** [yige233/fast_yiban#6]
我这边通过黄鸟找到的提交数据str，我复制粘贴到?sign_data=里面，提示sign_data的数据格式不正确，是我漏了一些特定的参数吗，

这是我用黄鸟抓到的
Str=SFBZOHBlalBKajcxUjRtczZHWW94TER4SmhobzhBVTVjbFQrN01LZFhZVUNHTVZQYTE0WFNJY1RoZ3ZFelVzZ1dqUkM2Wm9HTnFxMkhUSjZkakZsRVZRM0kvRHJnYm5ORFBhUUYxUDdWZElPZnZ5cEZKdWd1SnVZQ0h5TUxpcWk5Wlc3Tmt0aFZqQkxYWGZkWVdYTjR1Rnp0ejJ2OFlYMTB0aCtGYUFTeG1SSVZxWkIwbkVSSjFZZGZMazE1Qkt6eXcyVGdzcWw5V3pZMGZQRmFxOEhacE5LSG5uV0tIdmI1VWE1eGhUUXhXUG8wc1YwU0x1MUVkTHppZ3FuZWUyeWp3Qis3U3c2UkY1ZkNuOVgvMm5IczVFTTd3ZUY0S1IyWUVjbGJIOG5aMnYyUFJPVTN0ZU9VbmVkVVp2cVNYVWpzMW84NEpmbVQrYVVDR0oyRzNuV042dERSSEh5dTlzTDF1L01QZGdxcjhBK3lFcFNXaTFRUm1qbVlEZU5rbWo0VWF1c0FLT0lVKzUwYUZsdUN2c0V3YldyWHVVbXREeUlIOWdrcGgwcVJGOFpSTGFZVHEyZHNnWW5PZjBMYW5OeitrL3k4SGV3ZWttYUQ0MDNSRnRkMHU0N0lBTnl5VUw2cHI0YWlqTG5wOFZHaG9QaVo3Q25wa1VWYVl3TzVKM3FiWEl1a1lhRVpsenBGWk53MnZsMms0ZEFaY2xtWnI4cDlCc2ZsN3R1dHVCNEVubWpaRUo4MmVnZ3FtVzB6N1Y3YVFVSkw4NVlwYXJIUGZ5N05uU1cyZHQzVVNpN0VjNVVSTnZzR1pXTG9rUUhkL0luVkl3ZkxDakNIUnZydm5vbmN4VUowUFl2UDYxWlAwU1laZFBLY0dQNmtpQzBOK2l4amdKVEdxU1BFa1Y3ajJGeThEeGoxdzNXRjdDdWIyYXR4enJOTkJ0aWpvSXk2MytkWEthVGwzeTE0ZlQzTWg5bDRtL0xhaEhRMnYxM1VqZ0pCWkVpQVM4WGtJUS9QMXlhNHpVRjV5b2dpY0U1YndlQW1JT3dwd01KWDRuenVVMUZrb0ZvR1FxejJSTGdnZG5qSVFPYzRTTmFaeHhPcndIWG5SaVo3R3VDY3c4aCtFYkdNakJmS2swSlZ6ZFYxWDBJZUlaeXFuTTB4bk5CRzVIdkxYanhtNkxYVlZLdDFJN1JsZUQyN0xDbDRQSVMvZDBuczRiTXZFOGlBV09LVXlrRWJ2cGVpV3ZONTVLTjlMYXJ5Q2xvMG1xNVhTNkJOSlRrRlFRUkxrNVF2Yit2alFHU0lWdTQvdlFuQlRDSFh6ZFh3YXVDbG1JS1Nma1RYU0pjUDFiQnJxc0NsVmk1YVlORlpCMmFjUjUzNlM2RU9rVGpjUk1HWnVGZUJnRDNjQmRsbWRZcFFIN2U2OE11Nng4Zjh3YlpBc1dyKzhQREdCY1BOM0xQSTQ1RVdmMEZiOGlZcXErV0R0V08zNFIzNmJ3T0ZmMGFHTGlCVm5rN2NvSlpvWlVacjIzYmxUb3R4Z0wzNnJidVZGbEdrYmU4ZVdiWFhBOTBvVkIvTitBM3R6cXVYSEhsbnFweHJHMm9SbFltbHZpcmdubVZCNDVUT1ZWR2xoSVdXUnUvOEhOOGh3eHJuWGhLUnpjN1FLcGZuQktUWVVjV01aazUvdVIwVk5PVGRjamYwcWx5L1lFS2lCVXNIZm5UamVzNEtkZVJqTzlWMWFBaUJkMCtCREExNzNxSmQxY1hxVUJNclBTeGI5dWhaLzdpK3UzSGVuSmpCd3pKSzI0WldRZ0d3emVSSVI1NDMzWm5TYU5Vb2c5OVpnQ1M4dlIzeDhwQlVMS1JuSnNZU3hMWkhNWlEyWHkzMlZYZ2t3N0JYelFsTXEvS2Q5d0xLeUozYVN3VmVUSzVSY0ZjSTdRNE5MNHJOSGlpU3NrbExvNmtYVVhyNHhWZ3dWWFphSXVPM0pkTmc1WDNpQ0tRd1Y5VjVuczU3V0dweDkvTW5iYkZGTWUxamRLSEpIdktROHpoTGNWV0JsNnQ0aFBDam1LR3JrY29xaFdCcFpwdWJKd3pHWHY1SWhEM0hnVDZyMkRMeGlpemxFMUE1dUY3TjJyVldSL0dUZXpmaTRtcU15Y1FmeVBZZlM2cjFzSGUyUVU1UDYzekVBSXo5UHlmRWRjMkNhWGh1K29RWlFNVTZGR01hSEt2Wk5vSTlkaUYrZlVUMGxUMmV4TlFORkc5bDNOcjE2RXFETjZxRS9tcnNJOWxxamRteHVJN0RMRDVBQkJxR0c0blhobG1adnVQ

**Comment by yige233** [comment]
你抓到的这个Str是易班加密过的，而我程序是将数据发送到服务器，再由服务器把数据加密成这个Str的样子，然后提交。两个数据不一样
因为直接用浏览器发送提交请求会有跨域问题，所以得用服务器提交
