### ISSUE TITLE
作者你好，我发现一个bug

### ISSUE THREAD

**Issue by SHIKO-ZHOU** [yige233/fast_yiban#7]
点击登录后就报错
![41728816ec2f0ae71928d177bb4b423](https://user-images.githubusercontent.com/54561881/203340288-0740ef9a-1bc0-4d67-b56f-8169c6c04be0.png)
![f80d3e09a9097488481b821f2c2d2a1](https://user-images.githubusercontent.com/54561881/203340296-5b2da612-40da-47df-9d63-8868a34686b6.png)

**Comment by SHIKO-ZHOU** [comment]
我使用你搭建的demo就没有问题

**Comment by yige233** [comment]
绷不住了，这里的问题是，websocket的协议ws后面少了打个冒号。。。
想了想是这样的：我的demo是https连接，所以websocket也要用wss协议；但我一开始没考虑到这种情况，所以部署时报错；因此把代码改成了根据http协议使用不同的ws协议。然后因为当时挺急的，ws后面就少打了个冒号。。。可以看到wss后面是带冒号的
