### ISSUE TITLE
本地和腾讯云运行都提示连接服务器时发生错误。

### ISSUE THREAD

**Issue by hange33** [yige233/fast_yiban#9]
![image](https://user-images.githubusercontent.com/45906760/203705590-5610878b-c43f-4325-851c-396d41b95f13.png)

**Comment by yige233** [comment]
问题源于：程序构建websocket url时，没有带上端口。[
修复：程序没有运行在80或443端口时，websocket url无效](https://github.com/yige233/fast_yiban/commit/fd7b702ba16afa60d44c7208b1ac7df384673774)

**Comment by hange33** [comment]
正常了，感谢大佬

**Comment by hange33** [comment]
现在直接访问ip:端口正常，但是走域名还会和以前一样

**Comment by yige233** [comment]
没能复现。请打开网页控制台（F12），找到控制台（Console），看看有无红色的报错（截图的话记得给域名打码

**Comment by hange33** [comment]
![image](https://user-images.githubusercontent.com/45906760/203887888-b7968d30-dc33-4b48-8489-317099412ba1.png)
直接访问ip只有第一个报错，但能正常使用

**Comment by yige233** [comment]
报第二个错误时，你是用的域名+端口的方式，还是用了Apache之类的软件，做了反向代理？

**Comment by hange33** [comment]
用的Nginx Proxy Manager反向代理

**Comment by yige233** [comment]
那看来你很可能是只反代了http，没有反代websocket
我是没用过Nginx Proxy Manager，但我在网上找到一张截图：
![image](https://user-images.githubusercontent.com/34409561/203905093-033d2c3b-a83c-4429-9c33-36b8772a40b2.png)
你可能需要把图中的`Websockets Support`或者类似的选项勾上
[https://www.jianshu.com/p/269255703982](https://www.jianshu.com/p/269255703982)

**Comment by hange33** [comment]
懂了谢谢
